### ISSUE TITLE
cannot find pre-trained model

### ISSUE THREAD

**Issue by vietvo89** [MetaMain/ViTRobust#1]
Hi

I cannot find your pre-trained model. It seems that it was deleted. Can you re-upload it?

Thanks

**Comment by MetaMain** [comment]
Hi, sorry about that. I don't know how that happened. I have restored the models. Please check the Drive now and I will close this issue. If you have any other problems feel free to contact me at: kaleel.mahmood@uconn.edu.

**Comment by vietvo89** [comment]
Thank @MetaMain for your prompt reply and address the issue quickly.

**Comment by suvaansh** [comment]
Hi @MetaMain, the link for the pre-trained models is not working again. Can you please restore it. Thanks!

**Comment by MetaMain** [comment]
Thanks for mentioning this. I am not sure why the model download link is not working but I've created a new one here: https://drive.google.com/drive/folders/1VpbvFPAKMw4mpRJRblJcTwwIsC5A_A0r?usp=sharing. The link has also been updated in the readme on our Github. Let me know if you have any issues downloading the models now and please remember to cite our work if you use our models. Thank you!
