### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for VisionTransformer:

### ISSUE THREAD

**Issue by vietvo89** [MetaMain/ViTRobust#2]
Hi @MetaMain 

I have downloaded your models and am following your instruction to reproduce your result. Step 4 in your instruction maybe not straightforward, particularly for someone who does not use Visual Studio tool like me. 

So I am trying to build my simple own script using python only to run your attack against pre-train models. I got an error when doing first test with ViT model for CIFAR10. 

```
RuntimeError: Error(s) in loading state_dict for VisionTransformer:
	size mismatch for transformer.embeddings.position_embeddings: copying a param with shape torch.Size([1, 197, 1024]) from checkpoint, the shape in current model is torch.Size([1, 5, 1024]).
```
Here is what setting I use.

```
device = torch.device("cuda")
numClasses = 10
imgSize = 32 # 32: CIFAR10; 224: ImageNet
batchSize = 8

config = CONFIGS["ViT-L_16"]
model = VisionTransformer(config, imgSize, zero_head=True, num_classes=numClasses)
dir = "models/ViT-L_16,cifar10,run0_15K_checkpoint.bin"
dict = torch.load(dir)
model.load_state_dict(dict)
model.eval()
```

**Comment by MetaMain** [comment]
Please try using image size 224x224x3 for CIFAR-10. This size is what ViT models are typically trained on.

**Comment by MetaMain** [comment]
I will close this issue now. If you have further problems let me know.

**Comment by zhuawoluxun** [comment]
Where can I find your model

**Comment by MetaMain** [comment]
https://uconn-my.sharepoint.com/:f:/g/personal/kaleel_mahmood_uconn_edu/EgkVWxG7wb5FlUkzDRhFMC4B_LawJR0cBsn92GZeyZ3lDg?e=pSS3QK

-KM
